# Generated by Django 5.1.2 on 2024-10-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='inn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='snils',
            field=models.CharField(max_length=10),
        ),
    ]
