# Generated by Django 5.1.2 on 2024-10-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_certificate_inn_alter_certificate_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='number',
            new_name='serial_number',
        ),
    ]
