# Generated by Django 5.1.2 on 2024-11-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_number_certificate_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='owner',
        ),
        migrations.AddField(
            model_name='myuser',
            name='certificates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ouner', to='mainapp.certificate'),
        ),
    ]
