# Generated by Django 5.1.2 on 2024-12-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_myuser_certificates_certificate_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='middle_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
